#!/usr/bin/with-contenv bash
# shellcheck shell=bash

DELUGE_LOGLEVEL=${DELUGE_LOGLEVEL:-info}

# downlad latest GeoIP.dat after aged a week
geoip_dat_path="/usr/share/GeoIP/GeoIP.dat"
echo "[info] Checking GeoIP.dat ($geoip_dat_path)..."

if [ -e "$geoip_dat_path" ]; then
    current_time=$(date +%s)
    # file's modification and creation times in seconds since epoch
    modification_time=$(stat -c %Y "$geoip_dat_path")
    creation_time=$(stat -c %W "$geoip_dat_path")
    week_seconds=$((7 * 24 * 60 * 60))

    if (((current_time - modification_time) > week_seconds)) || (((current_time - creation_time) > week_seconds)); then
        echo "[info] Found outdated GeoIP.dat...updating (timeout 30s)"
        curl -s -L --retry 3 --retry-max-time 30 --retry-all-errors \
            "https://mailfud.org/geoip-legacy/GeoIP.dat.gz" |
            gunzip >$geoip_dat_path
    fi
else
    echo "[info] No GeoIP.dat found...updating (timeout 30s)"
    curl -s -L --retry 3 --retry-max-time 30 --retry-all-errors \
        "https://mailfud.org/geoip-legacy/GeoIP.dat.gz" |
        gunzip >$geoip_dat_path
fi

if [[ -f /config/core.conf ]]; then
    DELUGED_PORT=$(grep '"daemon_port"' /config/core.conf | tr -cd "[:digit:]")
fi

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z 127.0.0.1 ${DELUGED_PORT:-58846}" \
    s6-setuidgid abc /app/bin/deluged -c /config \
    -d --loglevel="${DELUGE_LOGLEVEL}"
