#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT APP
----------------------------------------------------------------------
WEBUI_PORTS=${WEBUI_PORTS}
DELUGE_LOGLEVEL=${DELUGE_LOGLEVEL}
----------------------------------------------------------------------
"

if [[ ! -s "${CONFIG_DIR}/GeoIP/GeoIP.dat" ]]; then
    echo "Getting \"GeoIP.dat\"..."
    mkdir -p "${CONFIG_DIR}/GeoIP"
    curl -sL "https://mailfud.org/geoip-legacy/GeoIP.dat.gz" | gunzip >"${CONFIG_DIR}/GeoIP/GeoIP.dat" 2>/dev/null
    chown -R hotio:hotio "${CONFIG_DIR}/GeoIP"
fi

if [[ ! -s "${CONFIG_DIR}/core.conf" ]]; then
    echo "Installing default \"core.conf\"..."
    install -m600 -o hotio -g hotio -t "${CONFIG_DIR}" "${APP_DIR}/core.conf"
fi
