#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ ! -f /config/core.conf ]]; then
    cp /defaults/core.conf /config/core.conf
fi

if [[ ! -f /config/ltconfig.conf ]]; then
    cp /defaults/ltconfig.conf /config/ltconfig.conf
fi

if [[ ! -f /config/trackercheck.conf ]]; then
    cp /defaults/trackercheck.conf /config/trackercheck.conf
fi
if [[ ! -f /config/web.conf ]]; then
    cp /defaults/web.conf /config/web.conf
fi
cp -f /defaults/plugins/*.egg /config/plugins/

mkdir -p /run/deluged-temp

# permissions
lsiown -R abc:abc \
    /run/deluged-temp \
    /config

# chown download directory if currently not set to abc
if [[ -d /downloads ]]; then
    if [[ "$(stat -c '%U' /downloads)" != "abc" ]]; then
        lsiown -R abc:abc /downloads
    fi
fi

# create torrents directory if it does not exist
if [[ ! -d /config/torrents ]]; then
    mkdir -p /config/torrents
    lsiown abc:abc /config/torrents
fi
